### ISSUE TITLE
Tx missing from /address/:address API

### ISSUE THREAD

**Issue by argvil19** [syscoin/blockbook#4]
Some SYS txs don't show up in API response. Kinda random, not sure how to reproduce.

Example
Address data: https://sys1.bcfn.ca/api/v2/address/sys1qny7vxk74dehyyymad7qtg7kzltxugfa30x2gws?details=txslight&pageSize=25&page=1&filter=0
tx involving sys1qny7vxk74dehyyymad7qtg7kzltxugfa30x2gws: https://sys1.bcfn.ca/tx/82a1727b0beeb5f210721a19cff964e7269dcdc2a989de1122ea5406d4c7fb44

**Comment by sidhujag** [comment]
this was fixed in 4.2
