### ISSUE TITLE
API v2 'address' arguments seem to not have any effect

### ISSUE THREAD

**Issue by bstr156** [syscoin/blockbook#5]
e.g.
`api/v2/address/tsys1q4u3uf53l965u9t6d4uej9c7dtaglk8jq2zxakh?filter=0` shows all, but is only supposed to show base coin tx
`api/v2/address/tsys1q4u3uf53l965u9t6d4uej9c7dtaglk8jq2zxakh?filter=tokens` shows all, but is only supposed to show token transfers

Not sure how critical this is, but would certainly be nice to have the functionality.

My instance of Syscoin Blockbook is up to commit hash 7e87ad35cdfc2c30d76e4ea6b68efa74fcca4eaa

**Comment by sidhujag** [comment]
can you retry on latest?

**Comment by bstr156** [comment]
Tried.  Same result.  Here is an address that has both base coin and SPT transactions.  Token transactions still showing up with filter=0
https://sys-explorer.tk/api/v2/address/tsys1q8e6xj8ajnntsnrujgyrsxmufhc98ys4j57c62f?filter=0

**Comment by sidhujag** [comment]
please see https://github.com/syscoin/blockbook/blob/master/docs/api.md#get-address
